# Generated by Django 5.2.1 on 2025-06-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_historicalusers_deleted_at_users_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.DeleteModel(
            name='HistoricalUsers',
        ),
    ]
