# Generated by Django 5.2.1 on 2025-05-17 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesproduct',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='historicalcategoriesproduct',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='historicalindicators',
            name='category_product',
        ),
        migrations.RemoveField(
            model_name='indicators',
            name='category_product',
        ),
        migrations.AddField(
            model_name='historicalindicators',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.categoriesproduct', verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='historicalproducts',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.categoriesproduct', verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='historicalproducts',
            name='measure_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.measureunits', verbose_name='Measure Unit'),
        ),
        migrations.AddField(
            model_name='indicators',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoriesproduct', verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.categoriesproduct', verbose_name='Product Category'),
        ),
        migrations.AddField(
            model_name='products',
            name='measure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.measureunits', verbose_name='Measure Unit'),
        ),
    ]
