# Generated by Django 5.2.1 on 2025-06-05 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_categoriesproduct_measure_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalindicators',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalindicators',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmeasureunits',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproducts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalproducts',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproducts',
            name='measure_unit',
        ),
        migrations.DeleteModel(
            name='HistoricalCategoriesProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalIndicators',
        ),
        migrations.DeleteModel(
            name='HistoricalMeasureUnits',
        ),
        migrations.DeleteModel(
            name='HistoricalProducts',
        ),
    ]
