# Generated by Django 5.2.1 on 2025-05-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusers',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='users',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activated/Deactivated'),
        ),
        migrations.AlterField(
            model_name='historicalusers',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user/profile/image/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activated/Deactivated'),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
