# Generated by Django 5.2.1 on 2025-06-05 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_remove_historicalindicators_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=100, verbose_name='Categories Expense Name')),
            ],
            options={
                'verbose_name': 'CategoryExpense',
                'verbose_name_plural': 'CategoriesExpense',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=100, verbose_name='Payment Type Name')),
            ],
            options={
                'verbose_name': 'PaymentType',
                'verbose_name_plural': 'PaymentTypess',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted At')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('business_name', models.CharField(max_length=150, verbose_name='Comapny Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Supplierss',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=100, verbose_name='Payment Voucher Name')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Voucherss',
            },
        ),
        migrations.CreateModel(
            name='Mermas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted At')),
                ('date', models.DateField(verbose_name='Fecha de emisión de merma')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Quantity')),
                ('lost_modey', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Dinero perdido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activated/Deactivated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Deleted At')),
                ('date', models.DateField(verbose_name='Fecha de Emisión de Factura')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('voucher_number', models.CharField(max_length=50, verbose_name='Número de Comprobante')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.paymenttypes')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.suppliers')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.vouchers')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['id'],
            },
        ),
    ]
