# Generated by Django 5.2.1 on 2025-06-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0002_historicalcategoriesexpense_historicalexpenses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vouchers',
            options={'ordering': ['id'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Voucherss'},
        ),
    ]
