# Generated by Django 5.2.1 on 2025-06-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesexpense',
            options={'ordering': ['id'], 'verbose_name': 'Category Expense', 'verbose_name_plural': 'Categories Expense'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoriesexpense',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Category Expense', 'verbose_name_plural': 'historical Categories Expense'},
        ),
        migrations.AlterModelOptions(
            name='historicalpaymenttypes',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Payment Type', 'verbose_name_plural': 'historical Payment Types'},
        ),
        migrations.AlterModelOptions(
            name='historicalsuppliers',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Supplier', 'verbose_name_plural': 'historical Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='historicalvouchers',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Voucher', 'verbose_name_plural': 'historical Vouchers'},
        ),
        migrations.AlterModelOptions(
            name='paymenttypes',
            options={'ordering': ['id'], 'verbose_name': 'Payment Type', 'verbose_name_plural': 'Payment Types'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'ordering': ['id'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='vouchers',
            options={'ordering': ['id'], 'verbose_name': 'Voucher', 'verbose_name_plural': 'Vouchers'},
        ),
    ]
