# Generated by Django 5.2.1 on 2025-06-07 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_categoriesexpense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.categoriesexpense'),
        ),
        migrations.AddField(
            model_name='historicalexpenses',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='expense.categoriesexpense'),
        ),
    ]
